language: 
    - java
jdk:
  - oraclejdk8

#before_script: cd /home/travis/build/TIBCOSoftware/bw6-plugin-maven/tree/master/Source/bw6-maven-plugin

script:
 - mvn clean
 - mvn compile
 - mvn package
  