language: 
    - java
jdk:
  - oraclejdk8
 
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  
script:
 - mvn clean deploy --settings .travis/settings.xml -DskipTests=true -B -U
 #- mvn clean deploy -P release --settings .travis/settings.xml

deploy:
    provider: releases
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: SujataDarekar/TestPlugin
      tags: true
      jdk: oraclejdk8