language: 
    - java
jdk:
  - oraclejdk8
 
cache:
  directories:
    - ~/.m2/repository
    
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  

script:
 - "echo \"<settings><servers><server><id>ossrh</id><username>\\$SONATYPE_USERNAME</username><password>\\$SONATYPE_PASSWORD</password></server></servers></settings>\" > /home/travis/.m2/repository/settings.xml"
 - mvn help:effective-settings
 - mvn clean deploy -P release --settings /home/travis/build/SujataDarekar/TestPlugin/.travis/settings.xml -Dgpg.passphrase=$GPG_PASSPHRASE
 - mvn --settings .travis/settings.xml clean  verify -Dgpg.passphrase=$GPG_PASSPHRASE
 - mvn --settings .travis/settings.xml -Dgpg.passphrase=$GPG_PASSPHRASE clean deploy -P release 
 #- mvn --settings .travis/settings.xml -Dgpg.passphrase=$GPG_PASSPHRASE clean deploy -P release
 #- mvn help:effective-settings
 # - mvn --settings .travis/settings.xml deploy -Dgpg.passphrase=$GPG_PASSPHRASE

deploy:
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: SujataDarekar/TestPlugin
      jdk: oraclejdk8